{
 "title": "General",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Status",
   "type": "table",
   "description": "Up = 1 - service up\nUp = 0 - service down",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "up" }
   ]
  },
  {
   "title": "Uptime",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "time() - topk(1, process_start_time_seconds) by (instance, job)"
    }
   ]
  },
  {
   "title": "CPU usage, % (for all cores)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[30s]) * 100",
     "legendFormat": "{{job}} - {{instance}}"
    },
    {
     "expr": "sum(rate(process_cpu_seconds_total[30s]) * 100)",
     "legendFormat": "Common"
    }
   ]
  },
  {
   "title": "Memory usage, Mb",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "dotnet_totalmemory / 1000000", "legendFormat": "{{job}} - {{instance}}" }
   ]
  },
  {
   "title": "Response time 90% quantile for last min, ms",
   "type": "graph",
   "description": "90% quantile means  that 90% of requests are proceeded less than value milliseconds",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(server_proceed_request_time_ms_bucket[1m])) by (le, endpoint, instance)) ",
     "legendFormat": "{{instance}} - {{endpoint}}"
    }
   ]
  },
  {
   "title": "Methods",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(server_status_code_count) by (method, instance)",
     "legendFormat": "{{instance}} - {{method}}"
    }
   ]
  },
  {
   "title": "Status codes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(server_status_code_count) by (code, instance)",
     "legendFormat": "{{instance}} - {{code}}"
    }
   ]
  }
 ]
}